export const posts: PostExt[] = [
  {
    id: "1",
    timestamp: 1634567890,
    files: [],
    mentions: [],
    content: "Item 1",
    hash: "hash1",
    target: undefined,
    source: undefined,
  },
  {
    id: "2",
    timestamp: 1634567891,
    files: [],
    mentions: [],
    content: "Item 2",
    hash: "hash2",
    target: undefined,
    source: undefined,
  },
  {
    id: "3",
    timestamp: 1634567892,
    files: [],
    mentions: [],
    content: "Item 3",
    hash: "hash3",
    target: undefined,
    source: undefined,
  },
  {
    id: "4",
    timestamp: 1634567893,
    files: [],
    mentions: [],
    content: "Item 4",
    hash: "hash4",
    target: undefined,
    source: undefined,
  },
  {
    id: "5",
    timestamp: 1634567894,
    files: [],
    mentions: [],
    content: "Item 5",
    hash: "hash5",
    target: undefined,
    source: undefined,
  },
];
